### ISSUE TITLE
hw: account quota for UTCBs

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#859] opened 2013-08-29 11:01 UTC
According to `base-hw/src/core/platform_thread.cc`, when creating a new thread via a CPU session, the new UTCB gets allocated at `core_env()->ram_session()`, which bypasses the appropriate quota accounting. Embedding UTCB into platform thread is not feasible because of alignment requirements.

**Comment by skalk** [comment] 2019-03-13 12:27
Actually that is an important issue to solve, although it lies around since years. It is not that easy to integrate in the existent generic core code + hw backend. The problem is that all cpu session quota handling is done via the internally used allocator. I see two short-term solutions. Either we add a kernel specific utcb size value that is substracted/add from the allocator quota when creating/destroying threads, or we change the alignment of the Cpu_thread_component so that it has no vtable, does not extend classes and uses the Platform_thread as first member with a corresponding alignment restriction. Any opinions on that?

**Comment by m-stein** [comment] 2019-03-13 13:15
To me the approach of accounting a kernel specific UTCB size sounds simpler to implement and less delicate (impossible to mess up alignment silently in the future).

**Comment by nfeske** [comment] 2019-03-13 13:22
I agree with @m-stein. To fix the accounting issue, let's just add the book keeping, similar to how the PD session performs the book keeping when allocating/freeing RAM dataspaces.

That notwithstanding, I also like the direction outlined by @skalk regarding the `Cpu_thread_component`. But that would be another issue.

**Comment by skalk** [comment] 2020-01-31 14:54
@nfeske: please have a look at this less invasive solution. I do not like much using the Allocator_guard this way, but the only alternative would be to get rid of it in the Cpu_session_component at all.

**Comment by m-stein** [comment] 2020-02-04 14:05
93907364ad710d9826710643325d25911c4730cc looks good to me. @skalk Thanks for dealing with this issue!

**Comment by nfeske** [comment] 2020-02-10 15:30
Merged to staging

**Closed** 2020-02-20 11:15 UTC
Labels: bug, fixed
