### ISSUE TITLE
support of non-executable memory regions

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#1723] opened 2015-09-29 09:29 UTC
As pointed out in #1722: To support non-executable memory regions a principal extension in the generic Genode rm_session_component is required to propagate the information to the platform specific implementation. Furthermore potentially extensions/adjustments of the used base-\* kernel are required.

**Comment by alex-ab** [comment] 2017-10-18 08:45
In principle I'm done. Please review. I will check some more places where we may have used attach instead of attach_executable.

**Comment by skalk** [comment] 2017-10-18 09:44
:+1: very cool alex-ab

**Comment by chelmuth** [comment] 2017-10-18 10:08
The patch series looks very good. Thanks @alex-ab!

**Comment by nfeske** [comment] 2017-10-18 11:26
That's great @alex-ab - especially that you got all the important kernels covered so quickly!

**Comment by alex-ab** [comment] 2017-10-18 12:55
In f59987df2530c7de822b09d769e21134261448b9  and 12417102bc24e237515cc487fd86c70daa789bec  I had to adapt mmap handling in libc to support executable memory (e.g. by Arora and Javascript). Please check.

**Comment by chelmuth** [comment] 2017-10-18 13:08
Looks good.

**Comment by chelmuth** [comment] 2017-10-19 11:44
The issue is marked fixed. Does this include 4333b4f?

**Comment by alex-ab** [comment] 2017-10-19 11:47
If you are strict, you may force me to open up a separate feature issue for 4333b4fa2236dc0306d368eadaca4ec2b1dd480a. The commit however is ready already.

**Comment by chelmuth** [comment] 2017-10-19 11:55
Merged the complete branch as 461a6fcff326f9621fe5937b8091236a8c30b863

**Closed** 2017-11-06 12:58 UTC
Labels: feature, fixed
