### ISSUE TITLE
Latest ISO image is 5 years old

### ISSUE THREAD

**Issue by notorand-it** [genodelabs/genode#1803] opened 2015-12-02 07:35 UTC
Latest ISO/whatever image is 5 years old.
Users won't even test it without an image to download: none is willing to build it himself.

**Comment by nfeske** [comment] 2015-12-02 11:03
I am closing this issue as a duplicate of #1000. In the comment https://github.com/genodelabs/genode/issues/1000#issuecomment-161260312, I try to explain the current situation. Please feel welcome to join the discussion there.

**Closed by nfeske** 2015-12-02 11:03 UTC
