### ISSUE TITLE
vbox: handle initial link state in network backend

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#2117] opened 2016-10-06 09:37 UTC

**Comment by trimpim** [comment] 2016-10-07 05:49
For me this patches crash vbox when booting in to a 64 bit Ubuntu 14.04 or Windows 7. A 32 bit Windows boots fine.
The error is:
page fault, pd='[init -> vbox]' thread='vCPU dispatcher' cpu=1 ip=0x13ce620 address=0x8

**Comment by chelmuth** [comment] 2016-10-18 10:48
I removed the `fixed` label because of @trimpim's post.

**Comment by alex-ab** [comment] 2016-10-26 11:12
Some more information. It may happen that, with this patch, the link state change is processed before the network model and the used data structure is ready initialized. The phenomena is that TMTimerSetMicro is called from DevE1000.cpp with a pTimer of null - which is normally initialized in e1kR3Construct. Somehow it must be take sure, that the network model is ready before sending link state to it (or delaying the registration of the signal handlers up to the point where it is known that the network model is ready). Please have a look.

**Comment by alex-ab** [comment] 2016-10-27 19:39
Please try following commit.

**Comment by cnuke** [comment] 2016-10-28 08:21
:+1:

**Comment by chelmuth** [comment] 2016-11-02 15:49
Does c33d4fb fix the issue?

**Comment by alex-ab** [comment] 2016-11-02 18:00
Yes, as far as i know.

**Comment by trimpim** [comment] 2016-11-03 10:05
Yes, the issue is fixed with this patch.

**Closed** 2016-11-30 12:38 UTC
Labels: bug, fixed
