### ISSUE TITLE
wifi_drv: various fixes

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode#1439] opened 2015-03-06 13:28 UTC

**Comment by cnuke** [comment] 2015-03-10 14:11
@nfeske or @chelmuth please merge the latest wifi_drv fixes from https://github.com/cnuke/genode/commits/issue%231439_2 to staging. That should fix the problems observed on 32bit platforms.

**Comment by nfeske** [comment] 2015-03-10 14:26
I reviewed and merged the patch series into staging.

As a general guideline, I would suggest to remove commented-out code completely from the source code. I am referring to https://github.com/cnuke/genode/commit/d5d3b945461f96194db4e8442e838492115a04fe

**Comment by chelmuth** [comment] 2015-03-11 06:48
@cnuke again I'd like to express that I'm impressed you found the cause of wrongly-named 32-bit issue :+1: I'm still shattered GCC added this empty-struct extension as these are not valid C99. So, if anybody knows about a solution to successfully compile Linux kernel code _and_ force compiler errors on empty structs, I'd like to hear about it.

**Comment by chelmuth** [comment] 2015-03-11 07:02
Hm, should we enable `-Wc++-compat` in dde_linux?

**Closed** 2015-03-13 11:18 UTC
Labels: bug
