### ISSUE TITLE
VFS symlink not checking path at readlink

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#1790] opened 2015-11-24 14:11 UTC
Readlink on the symlink builtin is missing a check on the incoming path, so the first symlink found can be read instead of the correct symlink that would be found further in the hierachy.

**Comment by nfeske** [comment] 2015-11-24 17:16
Merged to staging.

**Comment by nfeske** [comment] 2015-11-24 17:17
Oh, I just noticed that the issue is actually not marked as fixes. Have I merged it too quickly?

**Comment by ehmry** [comment] 2015-11-24 18:03
The difference between the first and second commit here is that the first one was not marked as fixed :\

**Closed** 2015-11-30 08:44 UTC
