### ISSUE TITLE
sculpt ce: installed package can stay in "installing" state in menu forever

### ISSUE THREAD

**Issue by tomga** [genodelabs/genode#3241] opened 2019-03-20 21:49 UTC
Attempt to install "download debian" package from cnuke's depot ends with:
```
[runtime -> update -> manager] Installation complete.
```
in the log but in menu it shows "installing..." forever and it isn't possible to start instance - it is not possible to assign "vm_fs".

Possibly it can be a result of earlier logs:
```
[runtime -> update] Warning: dynamic assigned RAM (24M) exceeds available RAM (24060830)
[runtime -> update] Error: RAM preservation exceeds available memory
```

I think that there is a problem with a package which triggers another with error handling.

**Comment by nfeske** [comment] 2019-03-21 09:21
I can reproduce this issue when starting with an empty ram fs. For some reason, the sculpt manager fails to interpret the state report of the update subsystem in the correct way. I'll investigate.

**Comment by nfeske** [comment] 2019-03-21 09:51
The problem is that @cnuke's pkg has a superfluous `<rom>` listed as its content in the runtime definition.

@cnuke could you please remove the `pthread.lib.so` entry and update the pkg and index? The pthread.lib.so does not exist anymore because the functionality is now part of the libc. The sculpt manager presents the configuration dialog only if the package is complete. But since the pthread.lib.so won't ever be installed, it remains incomplete even after the update mechanism has done its job.

**Comment by tomga** [comment] 2019-03-21 10:16
Shouldn't it be presented as "malformed package" or "installation error" or something like this?

**Comment by nfeske** [comment] 2019-03-21 10:17
Yeah. You are completely right.

**Comment by valerius2k** [comment] 2019-03-21 10:36
I acknowledge that this problem is caused by unneeded ROM modules. Yesterday, I updated my working copy from the repository, and encountered the same problem @tomga has. The same problem occurred with my own program. I had three unneeded ROM's. When I commented them out, my program now started successfully again.

**Comment by cnuke** [comment] 2019-03-21 10:57
Done.

**Comment by nfeske** [comment] 2019-03-21 11:43
Commit https://github.com/genodelabs/genode/commit/754a5959069a09647a7a212e225ea6b2f4dd3c33 implements @tomga's suggestion.

**Comment by ehmry** [comment] 2019-03-22 10:23
Is it possible to find out which ROMs are blocking a package? This issue is blocking the flif_capture package.

**Comment by nfeske** [comment] 2019-03-22 10:28
Yes, you can look in the blueprint of the queries package (/report/runtime/depot_query/blueprint) just after the failed installation. Look out for <missing_rom> nodes.

**Comment by ehmry** [comment] 2019-03-22 14:11
Excellent, thanks.

**Comment by nfeske** [comment] 2019-04-02 09:13
Fixed in master.

**Closed by nfeske** 2019-04-02 09:13 UTC
Labels: bug, fixed
