### ISSUE TITLE
device_pd (x86): virtual (non-device) memory mappings collide with 1:1 dma memory mappings (usb_drv problems with dynamic linking)

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#2209] opened 2016-12-22 20:19 UTC
Usb_drv no longer announces the Block service for me, and I have bisected the problem to ccffbb0dfce3fa85a152ad24b7c4494109ee5f8e.

I have a boot log here
https://gist.github.com/ehmry/853611e1c786b92acb5c6dfd684e613a

**Comment by ehmry** [comment] 2016-12-22 22:54
I was wrong, I now believe this to be a real hardware problem.

**Comment by chelmuth** [comment] 2016-12-23 08:45
Your log looks strange. Is this an Intel platform with Intel graphics? Also all those *assignment* messages puzzle me
```
[init -> log_lower] [platform_drv -> intel_fb_drv -> ] assignment of PCI device 0:2.0 succeeded
[init -> log_lower] [platform_drv -> intel_fb_drv -> ] assignment of PCI device 0:0.0 succeeded
[init -> log_lower] [platform_drv -> intel_fb_drv -> ] assignment of PCI device 0:3.0 succeeded
[init -> log_lower] [platform_drv -> audio_drv -> ] assignment of PCI device 0:3.0 succeeded
[init -> log_lower] [platform_drv -> nic_drv -> ] assignment of PCI device 0:1.0 succeeded
[init -> log_lower] [platform_drv -> usb_drv -> ] assignment of PCI device 0:1.0 succeeded
[init -> log_lower] [platform_drv -> ahci_drv -> ] assignment of PCI device 0:3.2 succeeded
[init -> log_lower] [platform_drv -> usb_drv -> ] assignment of PCI device 0:2.0 succeeded
```
Could you please check that this log message uses reasonable input values and formatting?

**Comment by chelmuth** [comment] 2016-12-23 08:52
Also the log shows DMAR (IOMMU) faults
```
[ 0] DMAR:0xffffffff810340b0 FRR:0 FR:0x6 BDF:0:1d:0 FI:0x02827000
[ 0] DMAR:0xffffffff810340b0 FRR:0 FR:0x6 BDF:0:1a:0 FI:0x0283d000
```
On x201, PCI 1d.0 and 1a.0 are EHCI USB controllers. That would explain why also simple DMA transactions do not finish.

**Comment by reet-** [comment] 2016-12-23 09:06
@chelmuth In our experience this does not indicate a general DMA failure. Such faults can be caused by EHCI controllers trying to access their reserved memory regions (RMRR) during init (see _Handling Requests to Reserved System Memory_ in the VT-d spec). You can check the ACPI DMAR table for the actual addresses of a platform.

**Comment by chelmuth** [comment] 2016-12-23 10:43
@reet- That's the task of our acpi_drv which logs detected RMRRs found in the DMAR. Nevertheless, this late in boot process the device should not access those RAM regions and the log messages hint some issue. usb_drv also implements the USB handover from BIOS to OS.

**Comment by reet-** [comment] 2016-12-23 12:12
@chelmuth If it is late in the boot process, it is def. strange.

**Comment by ehmry** [comment] 2016-12-23 14:09
That X201 really belongs in retirement, I'm not worried about it.

**Comment by ehmry** [comment] 2016-12-24 00:59
Now I can't use the intel_fb_drv on a different laptop when I have VT-d enabled by the BIOS.

https://gist.github.com/ehmry/a4f7413e88b9d2242c30a7828ae0070f

The plot thickens?

**Comment by alex-ab** [comment] 2016-12-25 07:51
@ehmry: I have seen something like this with 16.11, which should have be gone however after e93ef168a1a66756932e743afa0c9af0f51469b3 on master.

**Comment by alex-ab** [comment] 2017-01-06 17:46
@ehmry: we found the issue - please try to replace in device_pd/target.mk 'base' with 'base-nova' - which helped for me.

However the problem may at any time happen again - to actually solve the issue, I think we can't avoid to re-work the platform_drv <-> device_pd handling structurally.

**Comment by ehmry** [comment] 2017-01-07 10:27
@alex-ab, yes, that fixes it for me, thank you

**Comment by nfeske** [comment] 2017-02-28 16:22
Fixed in Genode 17.02

**Comment by alex-ab** [comment] 2017-02-28 16:26
To quote myself:

> However the problem may at any time happen again - to actually solve the issue, I think we can't avoid to re-work the platform_drv <-> device_pd handling structurally.

Please let open until this gets really fixed. I plan to do it as soon as I find the free time slot.

**Comment by nfeske** [comment] 2017-02-28 16:28
@alex-ab thanks for keeping an eye on my manic issue-closing assault. ;-)

**Comment by alex-ab** [comment] 2017-08-02 16:16
Now had the time to look into. Thx @nfeske for the discussion and pointers.

**Comment by alex-ab** [comment] 2017-08-18 08:36
@chelmuth: please consider for staging eb5bce5f79468b87656d4403a0622e4677c2fa7f

**Closed** 2017-08-30 10:49 UTC
Labels: bug, fixed
