### ISSUE TITLE
window_layouter: dynamic screen handling

### ISSUE THREAD

**Issue by skalk** [genodelabs/genode#3646] opened 2020-02-11 13:35 UTC

**Comment by skalk** [comment] 2020-02-11 13:40
Although, there is already rudimentary support for having more than one "screen" in the window_layouter's configuration, it does not allow to dynamically switch in between of those. When having more than 3 or 4 windows, which overlap heavily or stay fullscreen it is tiring to use the switch-in-between-windows shortcut. Therefore, it would be nice to first switch in between different screens via keyboard shortcuts.

**Comment by nfeske** [comment] 2020-02-13 10:58
Thanks for this cool feature. Can't wait to merge (and use) it. Please find my nitpicks as inline comments.

**Comment by skalk** [comment] 2020-02-13 15:17
@nfeske ok, I've incorporated the points you made

**Comment by nfeske** [comment] 2020-02-13 15:58
Very good. I merged your new patch along with my minor fixup https://github.com/genodelabs/genode/commit/a67be171cb76be7b82202172e8d1be0d31cd025d. May you give the result another spin?

**Comment by skalk** [comment] 2020-02-17 14:25
I gave it a try, and it seems to work as expected.

**Closed** 2020-02-20 11:15 UTC
Labels: fixed

**Comment by nfeske** [comment] 2020-03-27 14:22
Unfortunately, the screen-handling feature introduced a regression that I noticed today while experimenting with the tiling features of the window layouter. The tiling no longer works. (This made me wonder during my FOSDEM presentation actually, but back then, I brushed it aside as a typo or something).
 
In https://github.com/genodelabs/genode/commit/3c830c18e7c305841305345b477fe32e1d37e082, I reverted the offending part of the patch and thereby restored the original behavior. The dynamic screen handling still seems to work well, which suggests that the dropped condition was probably an accident.

@skalk Can you remember the thoughts behind this particular change? Do you think that restoring the condition will break the dynamic screen handling in some way?

**Comment by nfeske** [comment] 2020-03-27 15:14
BTW, I updated my Sculpt 20.02 index with the fixed version. So you can easily give it a try.

**Comment by nfeske** [comment] 2020-03-30 13:53
Some further testing with my commit reveals that it introduces a problem: In the rules, the geometric attributes of several assign nodes become zero, which is not intended. I'll investigate this further.

**Comment by nfeske** [comment] 2020-03-30 15:34
Commit https://github.com/genodelabs/genode/commit/c6efef1d894335c5e4edbdfbd13582f52baa3cb4 fixes the problem by implementing the support for multiple screen targets and making the distinction between visible and invisible targets explicit. The original version of the dynamic-screen feature created only one screen target. With only the first screen present in the list of targets, windows on invisible screens would naturally never match any target. The dropped condition covered up this missing part of the implementation.
