### ISSUE TITLE
tool chain: improve 'autoconf' version selection

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4622] opened 2022-09-28 06:24 UTC
On Ubuntu 22.04 `autoconf2.69` is needed, but on Ubuntu 20.04 it's `autoconf` (which is version 2.69 as well).

**Comment by cproc** [comment] 2022-09-29 06:17
Fixed by 492a3aa.

**Comment by chelmuth** [comment] 2022-09-29 07:42
Great, it seems to work as intended - x86 was built successfully, other platforms are in the queue. Merged the commit to staging.

**Closed** 2022-10-12 12:33 UTC
Labels: fixed
