### ISSUE TITLE
hw: send exception signals and support single-stepping

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#4975] opened 2023-08-08 09:01 UTC

**Comment by cproc** [comment] 2023-08-08 09:07
Commit e2c351a implements the features for x86_64 and arm_64.

**Comment by cproc** [comment] 2023-08-09 11:02
Fixup commit 2a0e475 prints a warning if an exception occured and no exception handler is registered and calls `_die()` if the exception could not be handled for other reasons. The behavior if no exception handler is registered is still a bit different than before, because the information if a signal handler is  registered is stored in the `Pager_object` and doesn't seem to be easily accessible from the kernel exception handler and so the warning is printed at a CPU architecture-independent place without the CPU architecture-specific exception type and I don't know how to mark the thread as dead from there like it was done before (and if it is really necessary).

**Comment by chelmuth** [comment] 2023-08-09 11:29
I merged the fixup and suggest to wait what's @skalk's stance on the remaining questions.

**Comment by cproc** [comment] 2023-08-10 05:16
Fixup commit cbe76b1 fixes the base-foc-rpi3 build error reported by the nightly builder.

**Comment by skalk** [comment] 2023-08-21 10:15
@cproc @chelmuth: Regarding the general solution, I'm a bit unhappy about the core code, which is accessing kernel-specific thread structures directly here without specific kernel-syscalls for it (and thereby synchronization). This is somehow possible as long as it is under all circumstances guaranteed that the thread is not scheduled or executable at all whenever `state()` or `exception_state()` is called by the core-thread. In my eyes it would be better to use designated kernel-syscalls to return the state and to implement the single-step feature, and thereby guarantee synchronized access.
Moreover, the introduction of further state variables within the kernel's thread object is something I'm struggling with. We already have numerous state variable in the thread object, like _state, _paused, etc. Although I can understand that it overstretches this issue to consolidate that. We potentially can do this afterwards, but it definitely worsens the state defibration.


> Fixup commit 2a0e475 prints a warning if an exception occured and no exception handler is registered and calls _die() if the exception could not be handled for other reasons. The behavior if no exception handler is registered is still a bit different than before, because the information if a signal handler is registered is stored in the Pager_object and doesn't seem to be easily accessible from the kernel exception handler and so the warning is printed at a CPU architecture-independent place without the CPU architecture-specific exception type and I don't know how to mark the thread as dead from there like it was done before (and if it is really necessary).

I think it is okay to not call `_die()` here,as far as I understood the implementation correctly in this case the thread is implicitely not executable and gets paused? Normally, marking the thread as being dead is done to ensure it does not get executed any longer.

**Comment by skalk** [comment] 2023-08-21 11:51
@cproc would you add designated syscalls for at least to check the exception state, and to set the single-step feature? Or do you want me to do so? I think, we can keep the state extension until the state handling of the whole Thread class gets consolidated.

**Comment by cproc** [comment] 2023-08-21 12:24
@skalk: I've started with a syscall for obtaining the CPU state and it seems to be working already. I'm going to add the other syscalls as well.

**Comment by cproc** [comment] 2023-08-21 14:16
Fixup commit 9967580 adds the syscalls.

**Comment by chelmuth** [comment] 2023-09-22 07:57
Commit 8b7f95945164397f1b54a925a037834f5d513000 breaks run/vmm_arm (on imx8q_evk as well as virt_qemu_arm_v8a). If I revert the commit current staging the test succeeds.

**Comment by cproc** [comment] 2023-09-26 17:13
> Commit [8b7f959](https://github.com/genodelabs/genode/commit/8b7f95945164397f1b54a925a037834f5d513000) breaks run/vmm_arm (on imx8q_evk as well as virt_qemu_arm_v8a). If I revert the commit current staging the test succeeds.

I changed the VM exception vector to take the new `Cpu_state::ec` member into account in commit e33cf2f, but unfortunately the test still does not succeed and I have no idea what else could be the problem.

**Comment by cproc** [comment] 2023-09-26 17:54
When I revert commit 8b7f959 and then apply only the part which adds the `Cpu_state::ec` member (f0dad75), the `vmm_arm` test fails as well with and without the VM exception vector change, so at least we know that the problem has something to do with the addition of this member.

**Comment by skalk** [comment] 2023-09-27 07:43
@cproc the virtualization world switch assembler path is inherently bound to the Cpu_state's layout. Therefore, it breaks if a new member is inserted somewhere in between.
I wonder to which hardware register `ec` (exception class) correlates? Do you mean "ESR_EL0", in that case exception class is a sub-bitfield of it. Or does it reflect no hardware register but only a hardware state abstraction?
Actually, by now we use Cpu_state for concrete hardware registers, and in base-hw it is used as foundation for a thread's state or a vm's state (where even more system register are part of). If for some reasons, you wanted to add the ESR_EL0 register to the common Cpu_state, we should remove it from the virtualization extensions vice versa.

**Comment by cproc** [comment] 2023-09-27 10:40
@skalk: `ec` correlates to the `EC` part extracted from `ESR_EL1`, so it is more like an abstraction similar to `trapno` in the x86 `Cpu_state`.

**Comment by skalk** [comment] 2023-09-27 14:27
If it is no real abstraction of potential exception types, but a 1:1 bit-shifted representation of ESR_EL1::EC, then it would be beneficial in my eyes to better use a copy of ESR_EL1, and name it accordingly. Thereby, we could also remove the resulting duplicate of ESR_EL1 from the virtualization extension of the Cpu_state.

**Comment by cproc** [comment] 2023-10-02 10:07
Commit a0480b7 moves `ESR_EL1` to the `Cpu_state` and fixes the `vmm_arm` test. Apparently the members of the VCPU state need to be correctly aligned for the `ldp/stp` instructions for the test to work, so I adapted the layout accordingly.

**Comment by skalk** [comment] 2023-10-02 11:24
@cproc impressive, thank you for considering my objection! Now, the virtualization works like a charm.

**Closed** 2023-10-04 11:24 UTC
Labels: fixed
