### ISSUE TITLE
rump: rump_fs and vfs+rump_fs plugin don't write all data to disk

### ISSUE THREAD

**Issue by alex-ab** [genodelabs/genode#2677] opened 2018-02-12 14:11 UTC
Using rump_fs server or vfs + rump_fs plugin may produce corrupted data.

I tracked down the issue to missing functionality in the [rump vfs contrib sources](https://github.com/NetBSD/src/blob/trunk/sys/rump/librump/rumpvfs/vm_vfs.c#L67) compared to the [original uvm_pager](https://github.com/NetBSD/src/blob/trunk/sys/uvm/uvm_pager.c#L436) sources of NetBSD. The [error case](https://github.com/NetBSD/src/blob/trunk/sys/uvm/uvm_pager.c#L380) in the orignal uvm pager code is not covered by the [rump vfs contrib sources](https://github.com/NetBSD/src/blob/trunk/sys/rump/librump/rumpvfs/vm_vfs.c#L67).

**Comment by alex-ab** [comment] 2018-02-12 14:27
After adjusting the rump vfs layer accordingly to the orignal uvm_pager code my test case successfully terminates.

**Comment by nfeske** [comment] 2018-02-12 14:38
@alex-ab Wow - you found the needle in the haystack! Hats off for the impressive feat of finding the root cause of this long-standing uncertainty! Thank you very very much for your patience. I merged your fix to staging.

**Comment by krytarowski** [comment] 2018-02-13 04:42
Is this applicable for the upstream sources as well? (In NetBSD's src/).

**Comment by cnuke** [comment] 2018-02-13 07:37
Yes, although it might needs some proper review as it is merely copy of original implementation (I am not sure if rump handles the PG_FAKE case or needs it at all).

**Comment by krytarowski** [comment] 2018-02-13 16:45
We keep developing rump in the NetBSD (mostly for the purpose of tests), best to keep forks in sync as much as possible.

**Comment by alex-ab** [comment] 2018-02-15 09:31
I reported the issue to the [rump kernel user mailing list](https://www.freelists.org/post/rumpkernel-users/Missing-error-handling-in-rumpvfsvm-vfsc) and based on the suggestion by Antti Kantee opened a NetBSD bug report [53032](http://gnats.netbsd.org/53032).

**Closed** 2018-02-16 08:23 UTC
Labels: bug, fixed
