### ISSUE TITLE
Port of edb (Evan's Debugger)

### ISSUE THREAD

**Issue by ghost** [genodelabs/genode#195] opened 2012-05-03 20:14 UTC
Some information about the debugger:
One of the main goals of this debugger is modularity. The interface is written in Qt4 and is therefore source portable to many platforms. The debugger core is a plugin and the platform specific code is isolated to just a few files, porting to a new OS would require porting these few files and implementing a plugin which implements the DebuggerCoreInterface interface. Also, because the plugins are based on the QPlugin API, and do their work through the DebuggerCoreInterface object, they are almost always portable with just a simple recompile.

http://codef00.com/projects#debugger

**Comment by skalk** [comment] 2019-03-06 10:09
I do not see anybody working on this. The user that opened the issue is not available anymore, so I close the issue.

**Closed by skalk** 2019-03-06 10:09 UTC
Labels: feature
