### ISSUE TITLE
DHCP request fails in VirtualBox with ICH9 chipset

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#1044] opened 2014-01-31 17:22 UTC
When running the 'lwip' test in VirtualBox (4.3.6) with the 'ICH9' chipset configured, the DHCP request times out. With the 'PIIX3' chipset the problem did not occur.

**Comment by jjkarcher** [comment] 2018-03-29 23:49
I'd like to see if it's possible to get networking to work in VirtualBox with Sculpt EA, even if it means hacking the driver a little bit.

I don't know if the problem is the same after all this time.  Using PIIX3, I get the following lines in the log that seem to be the problem:

[runtime -> nic -> nic] PCI BIOS has not enabled device 00:3.0! Updating PCI command 0003->0007
[drivers -> platform_drv] Error: runtime -> nic -> nic: assignment of PCI device 0:3.0 failed phys=0xdc018000 virt=0x1000

I made some clumsy attempts at poking into the structures (in "repos/dde_ipxe/src/lib/dde_ipxe/nic.c" and "repos/os/src/drivers/platform/spec/x86/irq.cc") to hard-code the IRQ to 10 as suggested above, but it continues to use the original IRQ.

How do you hard-code the IRQ?

**Comment by chelmuth** [comment] 2018-04-03 07:43
Did you try to enable the `force_ioapic="yes"` config attribute in vbox as implemented in #2029?

**Comment by alex-ab** [comment] 2018-06-13 06:34
Fixed by #2801.

**Closed by alex-ab** 2018-06-13 06:34 UTC
Labels: bug
