### ISSUE TITLE
noux_tool_chain_auto test hangs on hw_x86_64

### ISSUE THREAD

**Issue by cproc** [genodelabs/genode#2873] opened 2018-06-18 17:03 UTC
Since commit [1], the 'noux_tool_chain_auto' test hangs pretty early on hw_x86_64 (`Signal_receiver::_platform_begin_dissolve()` does not return in that situation).

[1] https://github.com/genodelabs/genode/commit/a38ec2854a770ff8fb9688e89055e0c6e0b2e558

**Comment by alex-ab** [comment] 2018-11-29 09:17
Duplicate of #3063

**Closed by alex-ab** 2018-11-29 09:17 UTC
Labels: bug
