### ISSUE TITLE
Sculpt: use lwIP for fetching archives

### ISSUE THREAD

**Issue by ehmry** [genodelabs/genode#3252] opened 2019-03-22 13:53 UTC
The lwIP stack has lower throughput than lxip, but boots faster and is generally more reliable.

**Comment by ehmry** [comment] 2019-03-22 13:56
I have a patch for lwIP that is important and should be applied regardless of Sculpt at 2f1d5e9ad32861471c81ea7ac7fc133ddab388d3.

The patch to switch Sculpt stacks is at 71b37411ffe2a15dc0a54a04e797dc2735c2ef87.

**Comment by ehmry** [comment] 2019-03-22 15:15
I did a benchmark with my watch and a T420 with ethernet:

| package | stack | time |
--- | --- | ---
| tyrquake | lxip | 0:56 |
| tyrquake | lwip | 0:46 |
| arora | lxip | 1:07 |
| arora | lwip | 0:28 |

**Comment by nfeske** [comment] 2019-03-25 09:07
It's good to see lwIP to be feasible for Sculpt again. Thanks @ehmry for the great improvement.

When I originally created Sculpt's update subsystem, I intended to use lwIP but found it in unreliable state. That was not the fault of lwIP but back then, the integration with the libc's socket fs did not work well. So I had to switch to lxIP back then, which worked fine. It's very good to see the situation of lwIP much improved now.

Now, however, I see a different issue. With Sculpt, we can currently observe a quite severe TCP/IP performance regression. E.g., loading a website in Arora has become unbearably slow. The same goes for the fetching of depot archives. Even subjectively, it feels like night and day (or in this case, day and night) compared to earlier versions of Sculpt. In my evening hours during the last week, I have intensively used Sculpt CE on my old x201. The subjective degradation of the experience is real.

Instead of sidestepping this issue by swapping out the IP stack, let us better stare it in the eye and find the actual problem. I actually suspect that the problem is not local to lxIP but stems from the integration (that is, our) code, e.g., superfluous socket-fs operations, overuse of signals, or exceptions raised on paths where they should not occur, or even the missing handling of network events so that network processing happens as a side effect of timeout handling only. Of course, I cannot put my finger on it, but there must be some issue like that.

Now that we see this behavior live on our machines, we have a proper incentive to rectify them. By looking away, the underlying problems will continue to lurk there.

Regarding the pros and cons of both TCP/IP stacks, both have areas where they shine. I agree with you that lwIP fits better for Sculpt because it is smaller (it puts less weight on the boot image, starts up quickly, and is fast enough). In contrast, when looking at gigabit networking, lxIP is battle tested and allowed us to attain excellent performance in the past. Let's try to revive the latter!

**Comment by ehmry** [comment] 2019-03-25 10:06
Does this mean we are committing to make improvements to the VFS?

**Comment by nfeske** [comment] 2019-03-25 10:09
Of course. Was there ever a question about it?

**Comment by ehmry** [comment] 2019-03-25 11:32
Ok, incoming patch...

**Comment by nfeske** [comment] 2019-11-19 14:35
I'm closing this issue because I'm not planning to swap out the TCP/IP stack used in Sculpt.

**Closed by nfeske** 2019-11-19 14:35 UTC
