### ISSUE TITLE
hw & cortex_a9: use SMP in general

### ISSUE THREAD

**Issue by m-stein** [genodelabs/genode#1312] opened 2014-12-04 14:52 UTC
By now we only have the ``is_smp`` method that returns false if we don't use SMP even if the platform supports SMP. This causes problems with at least VEA9X4 as we act in some situations as if there is no SMP. One solution would be to provide both ``has_smp`` and ``use_smp`` but I think its better to always use SMP if there is support for it.

**Comment by chelmuth** [comment] 2015-01-05 19:54
I'm a bit confused about all the attached _confirmed_ and _fixed_ labels while the quickfix in master does not close the issue. Can we close this or remove the labels?

**Comment by m-stein** [comment] 2015-08-18 14:55
As the work at the USB armory got stuck a little in the past, I decided to meanwhile re-base the working branch of this issue. The VEA9X4 support was the only reason why the commits once didn't make it to staging and recently, the support for this platform was removed. Much has changed in base-hw since the last time I worked on this issue, so it took me some time to re-base. Now it does compile again but while re-basing and thereby reading about the ARM memory model again, I've found some bugs in the old state regarding the cache/TLB maintenance. Some mnemonics that don't mention a range for the affected processors do consider the shareability attributes of the affected pages instead and some don't. In some cases the latter affect all processors and in some they affect only the local one. Our implementations assume that mnemonics without a range postfix always consider the page attributes. This must be fixed.

**Comment by skalk** [comment] 2016-01-12 10:09
@m-stein please have a look at the last 6 commits of my topic branch https://github.com/skalk/genode/commits/issue%231312
These commits incorporate SMP for Cortex A9 and L2 cache enabling into current staging. I tried to incorporate your previous work as much as possible.

**Comment by m-stein** [comment] 2016-01-14 22:48
@skalk These commits look great. Thank you that you did this unpleasant work, the rebasing and refactoring etc.. There is only one inline comment in the first commit and then one general issue I'd like to mention. Back when we started implementing SMP in base-hw, I think, @nfeske said that we should not expend to much effort in order to optimize the UP case. You now do this, especially in the first (crt0.s, init.cc) and the last commit (TLB flushes). I'm fine with your differentiation, but I wonder if @nfeske has the same opinion.

**Comment by Kensan** [comment] 2016-01-15 10:44
I took the liberty of testing 95bb4ce on Muen. Unfortunately interrupt handling does not work properly since the Muen-specific **thread.cc** (which calls **pic()->irq_occured**) has been dropped. Please consider including commit 81618bee as it solves the issue for me.

**Comment by skalk** [comment] 2016-01-15 15:18
@m-stein I've incorporated your inline proposal. With respect to the SMP vs. UP differentiation my motivation was to lower the unnecessary abstractions that platforms had to implement, thereby reducing the overall complexity. I'll ask nfeske about it.

@Kensan thanks for the fixup, I've incorporated it into my commit.

**Closed** 2016-01-26 15:24 UTC
Labels: bug, fixed
